In [50]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv("titanic.csv")
df = df[["gender","survived"]]
df.dropna(inplace=True)
total = len(df)
print(total)

891

In [52]:
total_female = len(df[df["gender"]=="female"])
print("Total female : ", total_female)
total_male = len(df[df["gender"]=="male"])
print("Total male : ", total_male)

p_female = total_female/total
p_male = total_male/total

Total female :  314
Total male :  577

In [53]:
# marginal_probability of survival

total_survived = len(df[df["survived"]==1])
print("Total Survived :",total_survived)

total_do_not_survived = len(df[df["survived"]==0])
print("Total Did Not Survive :",total_do_not_survived)

p_survived = total_survived/total
p_not_survived = total_do_not_survived/total
print("Probability of Surviving :",p_survived)
print("Probability of Not Surviving :",p_not_survived)

Total Survived : 342
Total Did Not Survive : 549
Probability of Surviving : 0.3838383838383838
Probability of Not Surviving : 0.6161616161616161

In [54]:
print("\nMarginal Probabilities :")
print(f"P(gender == female):{p_female:.3f}")
print(f"P(gender == male):{p_male:.3f}")
print(f"P(survived == 1):{p_survived:.3f}")
print(f"P(survived == 0):{p_not_survived:.3f}")

Marginal Probabilities :
P(gender == female):0.352
P(gender == male):0.648
P(survived == 1):0.384
P(survived == 0):0.616

In [55]:
#joint probability
p_female_survived = len(df[(df["gender"]=="female") & (df["survived"]==1)])/total
p_female_not_survived = len(df[(df["gender"]=="female") & (df["survived"]==0)])/total

p_male_survived = len(df[(df["gender"]=="male") & (df["survived"]==1)])/total
p_male_not_survived = len(df[(df["gender"]==" male") & (df["survived"]==0)])/total

In [56]:
print("\nJoint Probabilities :")
print(f"P(female, survived == 1):{p_female_survived:.3f}")
print(f"P(female, survived == 0):{p_female_not_survived:.3f}")
print(f"P(male, survived == 1):{p_male_survived:.3f}")
print(f"P(male, survived == 0):{p_male_not_survived:.3f}")

Joint Probabilities :
P(female, survived == 1):0.262
P(female, survived == 0):0.091
P(male, survived == 1):0.122
P(male, survived == 0):0.000

In [57]:
# conditional probability of survival
p_survived_given_female = p_female_survived/p_female
p_survived_given_male = p_male_survived/p_male  
p_not_survived_given_female = p_female_not_survived/p_female
p_not_survived_given_male = p_male_not_survived/p_male
print("\nConditional Probabilities :")
print(f"P(survived == 1 | gender == female):{p_survived_given_female:.3f}")
print(f"P(survived == 1 | gender == male):{p_survived_given_male:.3f}")
print(f"P(survived == 0 | gender == female):{p_not_survived_given_female:.3f}")
print(f"P(survived == 0 | gender == male):{p_not_survived_given_male:.3f}")

Conditional Probabilities :
P(survived == 1 | gender == female):0.742
P(survived == 1 | gender == male):0.189
P(survived == 0 | gender == female):0.258
P(survived == 0 | gender == male):0.000

In [58]:
loan = pd.read_csv("loan_approval_dataset.csv")
loan

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,4267,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [59]:
#marginal probability of getting loan
getting_loan = len(loan[loan["loan_status"]=="Approved"])
not_getting_loan = len(loan[loan["loan_status"]=="Rejected"])

graduate_p = len(loan[loan["education"]==" Graduate"])
not_graduate_p = len(loan[loan["education"]=="Not Graduate"])

p_getting_loan = getting_loan/len(loan)
p_not_getting_loan = not_getting_loan/len(loan)

print(p_not_getting_loan)
self_emp = len(loan[loan["self_employed"]==" Yes"])
not_self_emp = len(loan[loan["self_employed"]==" No"])

print(self_emp)
print(not_self_emp)

print("\nMarginal Probabilities :")
print(f"P(getting loan):{p_getting_loan:.3f}")
print(f"P(not getting loan):{p_not_getting_loan:.3f}")

0.3778402436167721
2150
2119

Marginal Probabilities :
P(getting loan):0.622
P(not getting loan):0.378

In [60]:
#joint probability of getting loan and being graduate
p_getting_loan_graduate = len(loan[(loan["loan_status"]=="Approved") & (loan["education"]==" Graduate")])/len(loan)
p_self_employed_getting_loan = len(loan[(loan["loan_status"]=="Approved") & (loan["self_employed"]==" Yes")])/len(loan)
print
print("\nJoint Probabilities :")
print("\nJoint Probabilities :")
print(f"P(getting loan and being graduate):{p_getting_loan_graduate:.3f}")
print(f"P(getting loan and self-employed):{p_self_employed_getting_loan:.3f}")

Joint Probabilities :

Joint Probabilities :
P(getting loan and being graduate):0.314
P(getting loan and self-employed):0.313

In [63]:
#conditional probability of getting loan given being graduate
self_emp = len(loan[(loan["self_employed"]==" No") & (loan["loan_status"]=="Rejected")])
not_self_emp = len(loan[loan["self_employed"]==" No"])

not_self_employed_not_getting_loan = self_emp/not_self_emp
print("\nConditional Probabilities :")
print(f"P(not getting loan | not self-employed):{not_self_employed_not_getting_loan:.3f}")

Conditional Probabilities :
P(not getting loan | not self-employed):0.378

In [66]:
sachin = pd.read_csv("sachin_tendulkar.csv")
sachin

,Match_No,Innings,match_date,Versus,mode_of_dismissal,Runs,Balls_faced
0,1,1,1989-12-18 00:00:00,Pakistan,c Wasim Akram b Waqar Younis,0,2
1,2,2,1990-03-01 00:00:00,New Zealand,c & b S A Thomson,0,2
2,3,3,1990-03-06 00:00:00,New Zealand,c †I D S Smith b S A Thomson,36,39
3,4,4,1990-04-25 00:00:00,Sri Lanka,run out,10,12
4,5,5,1990-04-27 00:00:00,Pakistan,c Saeed Anwar b Imran Khan,20,25
...,...,...,...,...,...,...,...
447,459,448,2012-02-26 00:00:00,Australia,run out,14,15
448,460,449,2012-02-28 00:00:00,Sri Lanka,lbw b S L Malinga,39,30
449,461,450,2012-03-13 00:00:00,Sri Lanka,c D P M D Jayawardene b R A S Lakmal,6,19
450,462,451,2012-03-16 00:00:00,Bangladesh,c †Mushfiqur Rahim b Mashrafe Mortaza,114,147
451,463,452,2012-03-18 00:00:00,Pakistan,c Younis Khan b Saeed Ajmal,52,48

In [77]:
zoro = len(sachin[sachin["Runs"]==0])
total_innings = len(sachin)
prob_zoro = zoro / total_innings

shrilanka = len(sachin[sachin["Versus"]=="Sri Lanka"])
prob_shrilanka = shrilanka / total_innings

more_than_50 = len(sachin[sachin["Runs"]>=50])
prob_more_than_50 = more_than_50 / total_innings

bolls_faced_more_than_30 = len(sachin[sachin["Balls_faced"]>30])
prob_bolls_faced_more_than_30 = bolls_faced_more_than_30 / total_innings

print("Marginal Probabilities :")
print(f"Probability of getting zoro : {prob_zoro:.3f}")
print(f"Probability of playing against Sri Lanka : {prob_shrilanka:.3f}")
print(f"Probability of scoring more than 50 runs : {prob_more_than_50:.3f}")
print(f"Probability of facing more than 30 balls : {prob_bolls_faced_more_than_30:.3f}")

Marginal Probabilities :
Probability of getting zoro : 0.044
Probability of playing against Sri Lanka : 0.177
Probability of scoring more than 50 runs : 0.321
Probability of facing more than 30 balls : 0.522

In [86]:
Shri_Runs_50 = len(sachin[(sachin["Runs"]>=50) & (sachin["Versus"]=="Sri Lanka")])/total_innings
runs_0_dismissed = len(sachin[(sachin["Runs"] == 0) & (sachin["mode_of_dismissal"].str.startswith("c"))]) / total_innings
runs_30_balls_30 = len(sachin[(sachin["Runs"]>30) & (sachin["Balls_faced"]>30)])/total_innings
Pak_dismissed_lbw = len(sachin[(sachin["Versus"] == "Pakistan") & (sachin["mode_of_dismissal"].str.startswith("lbw"))]) / total_innings

#Joint Probability of scoring more than 50 runs and playing against Sri Lanka
print("\nJoint Probability :")
print(f"P(scoring more than 50 runs and playing against Sri Lanka):{Shri_Runs_50:.3f}")
print(f"P(scoring 0 runs and being dismissed by catch):{runs_0_dismissed:.3f}")
print(f"P(scoring more than 30 runs and facing more than 30 balls):{runs_30_balls_30:.3f}")
print(f"P(playing against Pakistan and being dismissed by lbw):{Pak_dismissed_lbw:.3f}")

Joint Probability :
P(scoring more than 50 runs and playing against Sri Lanka):0.055
P(scoring 0 runs and being dismissed by catch):0.031
P(scoring more than 30 runs and facing more than 30 balls):0.447
P(playing against Pakistan and being dismissed by lbw):0.013

In [94]:
print("\nConditional Probabilities :")

shri = len(sachin[(sachin["Versus"]=="Sri Lanka")])
least_50_runs_given_shri = len(sachin[(sachin["Runs"]>=50) & (sachin["Versus"]=="Sri Lanka")])
p_least_50_runs_given_shri = least_50_runs_given_shri / shri

morethan_30_balls = len(sachin[(sachin["Balls_faced"]>30)])
morethan_30_balls_morethan_30_runs = len(sachin[(sachin["Runs"]>30) & (sachin["Balls_faced"]>30)])
p_morethan_30_balls_morethan_30_runs = morethan_30_balls_morethan_30_runs / morethan_30_balls

runs_0 = len(sachin[sachin["Runs"]==0])
caught = len(sachin[(sachin["mode_of_dismissal"].str.startswith("c")) & (sachin["Runs"]==0)])
p_runs_0_caught = caught / runs_0

england = len(sachin[(sachin["Versus"]=="England")])
least_25_balls_eng = len(sachin[(sachin["Balls_faced"]>=25) & (sachin["Versus"]=="England")])
p_least_30_runs_given_eng = least_25_balls_eng / england

print(f"P(scoring more than 50 runs | playing against Sri Lanka):{p_least_50_runs_given_shri:.3f}")
print(f"P(scoring more than 30 runs | facing more than 30 balls):{p_morethan_30_balls_morethan_30_runs:.3f}")
print(f"P(scoring 0 runs | being dismissed by catch):{p_runs_0_caught:.3f}")
print(f"P(scoring more than 25 balls | playing against England):{p_least_30_runs_given_eng:.3f}")

Conditional Probabilities :
P(scoring more than 50 runs | playing against Sri Lanka):0.312
P(scoring more than 30 runs | facing more than 30 balls):0.856
P(scoring 0 runs | being dismissed by catch):0.700
P(scoring more than 25 balls | playing against England):0.649