In [1]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv("titanic.csv")
df = df[["gender","survived"]]
df.dropna(inplace=True)
total = len(df)
print(total)

891

In [52]:
total_female = len(df[df["gender"]=="female"])
print("Total female : ", total_female)
total_male = len(df[df["gender"]=="male"])
print("Total male : ", total_male)

p_female = total_female/total
p_male = total_male/total

Total female :  314
Total male :  577

In [53]:
# marginal_probability of survival

total_survived = len(df[df["survived"]==1])
print("Total Survived :",total_survived)

total_do_not_survived = len(df[df["survived"]==0])
print("Total Did Not Survive :",total_do_not_survived)

p_survived = total_survived/total
p_not_survived = total_do_not_survived/total
print("Probability of Surviving :",p_survived)
print("Probability of Not Surviving :",p_not_survived)

Total Survived : 342
Total Did Not Survive : 549
Probability of Surviving : 0.3838383838383838
Probability of Not Surviving : 0.6161616161616161

In [54]:
print("\nMarginal Probabilities :")
print(f"P(gender == female):{p_female:.3f}")
print(f"P(gender == male):{p_male:.3f}")
print(f"P(survived == 1):{p_survived:.3f}")
print(f"P(survived == 0):{p_not_survived:.3f}")

Marginal Probabilities :
P(gender == female):0.352
P(gender == male):0.648
P(survived == 1):0.384
P(survived == 0):0.616

In [55]:
#joint probability
p_female_survived = len(df[(df["gender"]=="female") & (df["survived"]==1)])/total
p_female_not_survived = len(df[(df["gender"]=="female") & (df["survived"]==0)])/total

p_male_survived = len(df[(df["gender"]=="male") & (df["survived"]==1)])/total
p_male_not_survived = len(df[(df["gender"]==" male") & (df["survived"]==0)])/total

In [56]:
print("\nJoint Probabilities :")
print(f"P(female, survived == 1):{p_female_survived:.3f}")
print(f"P(female, survived == 0):{p_female_not_survived:.3f}")
print(f"P(male, survived == 1):{p_male_survived:.3f}")
print(f"P(male, survived == 0):{p_male_not_survived:.3f}")

Joint Probabilities :
P(female, survived == 1):0.262
P(female, survived == 0):0.091
P(male, survived == 1):0.122
P(male, survived == 0):0.000

In [57]:
# conditional probability of survival
p_survived_given_female = p_female_survived/p_female
p_survived_given_male = p_male_survived/p_male  
p_not_survived_given_female = p_female_not_survived/p_female
p_not_survived_given_male = p_male_not_survived/p_male
print("\nConditional Probabilities :")
print(f"P(survived == 1 | gender == female):{p_survived_given_female:.3f}")
print(f"P(survived == 1 | gender == male):{p_survived_given_male:.3f}")
print(f"P(survived == 0 | gender == female):{p_not_survived_given_female:.3f}")
print(f"P(survived == 0 | gender == male):{p_not_survived_given_male:.3f}")

Conditional Probabilities :
P(survived == 1 | gender == female):0.742
P(survived == 1 | gender == male):0.189
P(survived == 0 | gender == female):0.258
P(survived == 0 | gender == male):0.000

In [58]:
loan = pd.read_csv("loan_approval_dataset.csv")
loan

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,4267,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [59]:
#marginal probability of getting loan
getting_loan = len(loan[loan["loan_status"]=="Approved"])
not_getting_loan = len(loan[loan["loan_status"]=="Rejected"])

graduate_p = len(loan[loan["education"]==" Graduate"])
not_graduate_p = len(loan[loan["education"]=="Not Graduate"])

p_getting_loan = getting_loan/len(loan)
p_not_getting_loan = not_getting_loan/len(loan)

print(p_not_getting_loan)
self_emp = len(loan[loan["self_employed"]==" Yes"])
not_self_emp = len(loan[loan["self_employed"]==" No"])

print(self_emp)
print(not_self_emp)

print("\nMarginal Probabilities :")
print(f"P(getting loan):{p_getting_loan:.3f}")
print(f"P(not getting loan):{p_not_getting_loan:.3f}")

0.3778402436167721
2150
2119

Marginal Probabilities :
P(getting loan):0.622
P(not getting loan):0.378

In [60]:
#joint probability of getting loan and being graduate
p_getting_loan_graduate = len(loan[(loan["loan_status"]=="Approved") & (loan["education"]==" Graduate")])/len(loan)
p_self_employed_getting_loan = len(loan[(loan["loan_status"]=="Approved") & (loan["self_employed"]==" Yes")])/len(loan)
print
print("\nJoint Probabilities :")
print("\nJoint Probabilities :")
print(f"P(getting loan and being graduate):{p_getting_loan_graduate:.3f}")
print(f"P(getting loan and self-employed):{p_self_employed_getting_loan:.3f}")

Joint Probabilities :

Joint Probabilities :
P(getting loan and being graduate):0.314
P(getting loan and self-employed):0.313

In [63]:
#conditional probability of getting loan given being graduate
self_emp = len(loan[(loan["self_employed"]==" No") & (loan["loan_status"]=="Rejected")])
not_self_emp = len(loan[loan["self_employed"]==" No"])

not_self_employed_not_getting_loan = self_emp/not_self_emp
print("\nConditional Probabilities :")
print(f"P(not getting loan | not self-employed):{not_self_employed_not_getting_loan:.3f}")

Conditional Probabilities :
P(not getting loan | not self-employed):0.378

In [66]:
sachin = pd.read_csv("sachin_tendulkar.csv")
sachin

,Match_No,Innings,match_date,Versus,mode_of_dismissal,Runs,Balls_faced
0,1,1,1989-12-18 00:00:00,Pakistan,c Wasim Akram b Waqar Younis,0,2
1,2,2,1990-03-01 00:00:00,New Zealand,c & b S A Thomson,0,2
2,3,3,1990-03-06 00:00:00,New Zealand,c †I D S Smith b S A Thomson,36,39
3,4,4,1990-04-25 00:00:00,Sri Lanka,run out,10,12
4,5,5,1990-04-27 00:00:00,Pakistan,c Saeed Anwar b Imran Khan,20,25
...,...,...,...,...,...,...,...
447,459,448,2012-02-26 00:00:00,Australia,run out,14,15
448,460,449,2012-02-28 00:00:00,Sri Lanka,lbw b S L Malinga,39,30
449,461,450,2012-03-13 00:00:00,Sri Lanka,c D P M D Jayawardene b R A S Lakmal,6,19
450,462,451,2012-03-16 00:00:00,Bangladesh,c †Mushfiqur Rahim b Mashrafe Mortaza,114,147
451,463,452,2012-03-18 00:00:00,Pakistan,c Younis Khan b Saeed Ajmal,52,48

In [77]:
zoro = len(sachin[sachin["Runs"]==0])
total_innings = len(sachin)
prob_zoro = zoro / total_innings

shrilanka = len(sachin[sachin["Versus"]=="Sri Lanka"])
prob_shrilanka = shrilanka / total_innings

more_than_50 = len(sachin[sachin["Runs"]>=50])
prob_more_than_50 = more_than_50 / total_innings

bolls_faced_more_than_30 = len(sachin[sachin["Balls_faced"]>30])
prob_bolls_faced_more_than_30 = bolls_faced_more_than_30 / total_innings

print("Marginal Probabilities :")
print(f"Probability of getting zoro : {prob_zoro:.3f}")
print(f"Probability of playing against Sri Lanka : {prob_shrilanka:.3f}")
print(f"Probability of scoring more than 50 runs : {prob_more_than_50:.3f}")
print(f"Probability of facing more than 30 balls : {prob_bolls_faced_more_than_30:.3f}")

Marginal Probabilities :
Probability of getting zoro : 0.044
Probability of playing against Sri Lanka : 0.177
Probability of scoring more than 50 runs : 0.321
Probability of facing more than 30 balls : 0.522

In [86]:
Shri_Runs_50 = len(sachin[(sachin["Runs"]>=50) & (sachin["Versus"]=="Sri Lanka")])/total_innings
runs_0_dismissed = len(sachin[(sachin["Runs"] == 0) & (sachin["mode_of_dismissal"].str.startswith("c"))]) / total_innings
runs_30_balls_30 = len(sachin[(sachin["Runs"]>30) & (sachin["Balls_faced"]>30)])/total_innings
Pak_dismissed_lbw = len(sachin[(sachin["Versus"] == "Pakistan") & (sachin["mode_of_dismissal"].str.startswith("lbw"))]) / total_innings

#Joint Probability of scoring more than 50 runs and playing against Sri Lanka
print("\nJoint Probability :")
print(f"P(scoring more than 50 runs and playing against Sri Lanka):{Shri_Runs_50:.3f}")
print(f"P(scoring 0 runs and being dismissed by catch):{runs_0_dismissed:.3f}")
print(f"P(scoring more than 30 runs and facing more than 30 balls):{runs_30_balls_30:.3f}")
print(f"P(playing against Pakistan and being dismissed by lbw):{Pak_dismissed_lbw:.3f}")

Joint Probability :
P(scoring more than 50 runs and playing against Sri Lanka):0.055
P(scoring 0 runs and being dismissed by catch):0.031
P(scoring more than 30 runs and facing more than 30 balls):0.447
P(playing against Pakistan and being dismissed by lbw):0.013

In [94]:
print("\nConditional Probabilities :")

shri = len(sachin[(sachin["Versus"]=="Sri Lanka")])
least_50_runs_given_shri = len(sachin[(sachin["Runs"]>=50) & (sachin["Versus"]=="Sri Lanka")])
p_least_50_runs_given_shri = least_50_runs_given_shri / shri

morethan_30_balls = len(sachin[(sachin["Balls_faced"]>30)])
morethan_30_balls_morethan_30_runs = len(sachin[(sachin["Runs"]>30) & (sachin["Balls_faced"]>30)])
p_morethan_30_balls_morethan_30_runs = morethan_30_balls_morethan_30_runs / morethan_30_balls

runs_0 = len(sachin[sachin["Runs"]==0])
caught = len(sachin[(sachin["mode_of_dismissal"].str.startswith("c")) & (sachin["Runs"]==0)])
p_runs_0_caught = caught / runs_0

england = len(sachin[(sachin["Versus"]=="England")])
least_25_balls_eng = len(sachin[(sachin["Balls_faced"]>=25) & (sachin["Versus"]=="England")])
p_least_30_runs_given_eng = least_25_balls_eng / england

print(f"P(scoring more than 50 runs | playing against Sri Lanka):{p_least_50_runs_given_shri:.3f}")
print(f"P(scoring more than 30 runs | facing more than 30 balls):{p_morethan_30_balls_morethan_30_runs:.3f}")
print(f"P(scoring 0 runs | being dismissed by catch):{p_runs_0_caught:.3f}")
print(f"P(scoring more than 25 balls | playing against England):{p_least_30_runs_given_eng:.3f}")

Conditional Probabilities :
P(scoring more than 50 runs | playing against Sri Lanka):0.312
P(scoring more than 30 runs | facing more than 30 balls):0.856
P(scoring 0 runs | being dismissed by catch):0.700
P(scoring more than 25 balls | playing against England):0.649

In [2]:
import pandas as pd

In [3]:
df_2015 = pd.read_csv("marathon_results_2015.csv")
df_2016 = pd.read_csv("marathon_results_2016.csv")
df_2017 = pd.read_csv("marathon_results_2017.csv")

In [9]:
df = pd.concat([df_2015, df_2016, df_2017])
df

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Unnamed: 8
0,0.0,3,"Desisa, Lelisa",25,M,Ambo,NaN,ETH,NaN,NaN,...,1:32:00,1:47:59,2:02:39,0:04:56,-,2:09:17,1,1,1,NaN
1,1.0,4,"Tsegay, Yemane Adhane",30,M,Addis Ababa,NaN,ETH,NaN,NaN,...,1:31:59,1:47:59,2:02:42,0:04:58,-,2:09:48,2,2,2,NaN
2,2.0,8,"Chebet, Wilson",29,M,Marakwet,NaN,KEN,NaN,NaN,...,1:32:00,1:47:59,2:03:01,0:04:59,-,2:10:22,3,3,3,NaN
3,3.0,11,"Kipyego, Bernard",28,M,Eldoret,NaN,KEN,NaN,NaN,...,1:32:00,1:48:03,2:03:47,0:05:00,-,2:10:47,4,4,4,NaN
4,4.0,10,"Korir, Wesley",32,M,Kitale,NaN,KEN,NaN,NaN,...,1:32:00,1:47:59,2:03:27,0:05:00,-,2:10:49,5,5,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26405,26405.0,25166,"Steinbach, Paula Eyvonne",61,F,Ontario,CA,USA,NaN,MI,...,5:03:08,5:55:18,6:46:57,0:16:24,-,7:09:39,26407,11972,344,NaN
26406,26406.0,25178,"Avelino, Andrew R.",25,M,Fayetteville,NC,USA,NaN,MI,...,4:50:01,5:53:48,6:54:21,0:16:40,-,7:16:59,26408,14436,4774,NaN
26407,26407.0,27086,"Hantel, Johanna",57,F,Malvern,PA,USA,NaN,NaN,...,5:06:37,6:00:33,6:54:38,0:16:47,-,7:19:37,26409,11973,698,NaN
26408,26408.0,25268,"Reilly, Bill",64,M,New York,NY,USA,NaN,MI,...,5:07:09,6:06:07,6:56:08,0:16:49,-,7:20:44,26410,14437,1043,NaN
26409,26409.0,25266,"Rigsby, Scott",48,M,Alpharetta,GA,USA,NaN,MI,...,5:37:13,6:39:07,7:41:23,0:18:15,-,7:58:14,26411,14438,2553,NaN

In [10]:
df[["Hours","Minutes","Seconds"]] = df["Official Time"].str.split(":", expand=True).astype(int)
df["finish_time_in_seconds"] = df["Hours"]*3600 + df["Minutes"]*60 + df["Seconds"]

In [11]:
df[["hours","minutes","seconds"]]=df["Pace"].str.split(":", expand=True).astype(int)
df["pace_in_seconds"] = df["hours"]*3600 + df["minutes"]*60 + df["seconds"]

In [12]:
condition_A = df["finish_time_in_seconds"]<=3*3600
condition_B = df["pace_in_seconds"]<8*60

In [15]:
#probability od A
p_A = len(df[condition_A])/len(df)
print(f"P(A):{p_A:.3f}")

#probability of B
p_B = len(df[condition_B])/len(df)
print(f"P(B):{p_B:.3f}")

#probability p(B|A)
p_B_given_A = len(df[condition_A & condition_B])/len(df[condition_A])
print(f"P(B|A):{p_B_given_A:.3f}")

P(A):0.070
P(B):0.305
P(B|A):1.000

In [16]:
# Bayes theorem
p_A_given_B = (p_B_given_A * p_A) / p_B
print(f"P(A|B):{p_A_given_B:.3f}")

P(A|B):0.229

In [20]:
titanic = pd.read_csv("titanic.csv")
titanic

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [41]:
#p(s=y,p=1)
condition_B = titanic["pclass"]==1
condition_A = titanic["survived"]==1

P_Class = len(titanic[condition_B])/len(titanic)
print(f"P(pclass == 1):{P_Class:.3f}")

P_survived = len(titanic[condition_A])/len(titanic)
print(f"P(survived == 1):{P_survived:.3f}")

P_Class_given_survived = len(titanic[condition_A & condition_B])/len(titanic[condition_A])
print(f"P(pclass == 1 | survived == 1):{P_Class_given_survived:.3f}")

p_survived_given_Class = (P_Class_given_survived * P_survived) / P_Class
print(f"P(survived == 1 | pclass == 1):{p_survived_given_Class:.3f}")

P(pclass == 1):0.242
P(survived == 1):0.384
P(pclass == 1 | survived == 1):0.398
P(survived == 1 | pclass == 1):0.630

In [43]:
df = pd.read_csv("Sachin_Tendulkar.csv")
df

,Match_No,Innings,match_date,Versus,mode_of_dismissal,Runs,Balls_faced
0,1,1,1989-12-18 00:00:00,Pakistan,c Wasim Akram b Waqar Younis,0,2
1,2,2,1990-03-01 00:00:00,New Zealand,c & b S A Thomson,0,2
2,3,3,1990-03-06 00:00:00,New Zealand,c †I D S Smith b S A Thomson,36,39
3,4,4,1990-04-25 00:00:00,Sri Lanka,run out,10,12
4,5,5,1990-04-27 00:00:00,Pakistan,c Saeed Anwar b Imran Khan,20,25
...,...,...,...,...,...,...,...
447,459,448,2012-02-26 00:00:00,Australia,run out,14,15
448,460,449,2012-02-28 00:00:00,Sri Lanka,lbw b S L Malinga,39,30
449,461,450,2012-03-13 00:00:00,Sri Lanka,c D P M D Jayawardene b R A S Lakmal,6,19
450,462,451,2012-03-16 00:00:00,Bangladesh,c †Mushfiqur Rahim b Mashrafe Mortaza,114,147
451,463,452,2012-03-18 00:00:00,Pakistan,c Younis Khan b Saeed Ajmal,52,48

In [48]:
condition_A = df["Runs"]>=50
p_A = len(df[condition_A])/len(df)
print(f"P(Runs >= 50):{p_A:.3f}")

condition_B = df["Versus"]=="Australia"
p_B = len(df[condition_B])/len(df)
print(f"P(Versus == Australia):{p_B:.3f}")

P_B_given_A = len(df[condition_A & condition_B])/len(df[condition_A])
print(f"P(Versus == Australia | Runs >= 50):{P_B_given_A:.3f}")
p_A_given_B = (P_B_given_A * p_A) / p_B
print(f"P(Runs >= 50 | Versus == Australia):{p_A_given_B:.3f}")

P(Runs >= 50):0.321
P(Versus == Australia):0.155
P(Versus == Australia | Runs >= 50):0.166
P(Runs >= 50 | Versus == Australia):0.343

In [49]:
import pandas as pd
df=pd.read_csv("loan_approval_dataset.csv")

import pandas as pd

# Load dataset

df.columns = df.columns.str.strip()

def bayes_probability(df):
    condition_A = df['loan_status'] == 1
    condition_B = df['education'].str.lower() == 'non_graduate'

    P_A = condition_A.mean()
    P_B = condition_B.mean()
    P_B_given_A = (condition_A & condition_B).sum() / condition_A.sum()
    P_A_given_B = (P_B_given_A * P_A) / P_B
    return P_A_given_B

# Initial probability
print("Initial P(Loan Approved | Non-Graduate):", bayes_probability(df))

# Function to add new record with 3 conditions
def add_new_customer(df, education, self_employed, loan_status):
    new_record = pd.DataFrame({
        'loan_id':[len(df)+1],
        'no_of_dependents':[0],
        'education':[education],
        'self_employed':[self_employed],
        'loan_status':[loan_status]
    })
    df = pd.concat([df, new_record], ignore_index=True)
    print(f"After adding {education}, Self Employed={self_employed}, Loan Status={loan_status}, new probability:", bayes_probability(df))
    return df

# Example usage:
df = add_new_customer(df, "Graduate", "No", 1)        # New Customer 1
df = add_new_customer(df, "Non_Graduate", "Yes", 0)   # New Customer 2
df = add_new_customer(df, "Non_Graduate", "No", 1)    # New Customer 3

Initial P(Loan Approved | Non-Graduate): nan
After adding Graduate, Self Employed=No, Loan Status=1, new probability: nan
After adding Non_Graduate, Self Employed=Yes, Loan Status=0, new probability: 0.0
After adding Non_Graduate, Self Employed=No, Loan Status=1, new probability: 0.5

C:\Users\ashis\AppData\Local\Temp\ipykernel_11536\1700839376.py:16: RuntimeWarning: invalid value encountered in scalar divide
  P_B_given_A = (condition_A & condition_B).sum() / condition_A.sum()
C:\Users\ashis\AppData\Local\Temp\ipykernel_11536\1700839376.py:17: RuntimeWarning: invalid value encountered in scalar divide
  P_A_given_B = (P_B_given_A * P_A) / P_B

In [50]:
import pandas as pd

# 1. Load dataset
df = pd.read_csv("loan_approval_dataset.csv")
df.columns = df.columns.str.strip()
print(df.head())

# 2. Initial counts
grad_total = len(df[df["education"] == "Graduate"])
grad_approved = len(df[(df["education"] == "Graduate") & (df["loan_status"] == "Approved")])

nongrad_total = len(df[df["education"] == "Not Graduate"])
nongrad_approved = len(df[(df["education"] == "Not Graduate") & (df["loan_status"] == "Approved")])

# 3. Initial probabilities (with safe division)
print("\nInitial probabilities")
if grad_total > 0:
    print("P(Approved | Graduate) =", round(grad_approved / grad_total, 4))
else:
    print("P(Approved | Graduate) = Not Defined (no Graduate records)")

if nongrad_total > 0:
    print("P(Approved | Not Graduate) =", round(nongrad_approved / nongrad_total, 4))
else:
    print("P(Approved | Not Graduate) = Not Defined (no Non-Graduate records)")

# -------------------------------
# 4. Add New Customer 1
education = input("\nCustomer 1 Education (Graduate/Not Graduate): ")
loan = input("Loan status (Approved/Rejected): ")

if education == "Graduate":
    grad_total += 1
    if loan == "Approved":
        grad_approved += 1
else:
    nongrad_total += 1
    if loan == "Approved":
        nongrad_approved += 1

print("\nUpdated probabilities after Customer 1")
if grad_total > 0:
    print("P(Approved | Graduate) =", round(grad_approved / grad_total, 4))
else:
    print("P(Approved | Graduate) = Not Defined")

if nongrad_total > 0:
    print("P(Approved | Not Graduate) =", round(nongrad_approved / nongrad_total, 4))
else:
    print("P(Approved | Not Graduate) = Not Defined")

   loan_id  no_of_dependents      education self_employed  income_annum  \
0        1                 2       Graduate            No       9600000
1        2                 0   Not Graduate           Yes       4100000
2        3                 3       Graduate            No       9100000
3        4                 3       Graduate            No       8200000
4        5                 5   Not Graduate           Yes       9800000

   loan_amount  loan_term  cibil_score  residential_assets_value  \
0     29900000         12          778                   2400000
1     12200000          8          417                   2700000
2     29700000         20          506                   7100000
3     30700000          8          467                  18200000
4     24200000         20          382                  12400000

   commercial_assets_value  luxury_assets_value  bank_asset_value loan_status
0                 17600000             22700000           8000000    Approved
1                  2200000              8800000           3300000    Rejected
2                  4500000             33300000          12800000    Rejected
3                  3300000             23300000           7900000    Rejected
4                  8200000             29400000           5000000    Rejected

Initial probabilities
P(Approved | Graduate) = Not Defined (no Graduate records)
P(Approved | Not Graduate) = Not Defined (no Non-Graduate records)

Updated probabilities after Customer 1
P(Approved | Graduate) = Not Defined
P(Approved | Not Graduate) = 0.0

In [51]:
# Binomial distribution
from scipy.stats import binom

# Given values
n=5 # Total number of students
k=3 # number of students whow like python
p=0.66 #Probability tgaht a student likes python

# Calculate binomial probability
probability=binom.pmf(k,n,p)

print(f"The probability that exactly {k} out of {n} student like Python is: {probability:.4f}")

The probability that exactly 3 out of 5 student like Python is: 0.3323

In [52]:
# CDF: P(X<=k)
cdf=binom.cdf(k,n,p)
print(f"CDF (P(X<={k})) ={cdf:.4f}")

CDF (P(X<=3)) =0.5522

In [53]:
from scipy.stats import binom
n=6
k=4
p=0.25

# Calculate binomial probability
probability=binom.pmf(k,n,p)

print(f"The probability that exactly {k} out of {n} patiant  is: {probability:.4f}")

The probability that exactly 4 out of 6 patiant  is: 0.0330

In [54]:
# CDF: P(X<=k)
from scipy.stats import binom
n=6
k=4
p=0.25
cdf=binom.cdf(k,n,p)
print(f"CDF (P(X< {k})) ={cdf:.4f}")

CDF (P(X< 4)) =0.9954

In [55]:
#(a) pro that exactly 4 recover
prob_exact_4=binom.pmf(4,n,p)
#(b) pro that more than 4 recover
prob_more_than_4=1-binom.pmf(4,n,p)
#(c) pro that exactly 4 recover
prob_more_than_4=binom.pmf(4,n,p)+binom.pmf(6,n,p)

print(f"Probability that exactly 4 recover={prob_exact_4:.4f}")
print(f"Probability that more than 4 recover={prob_more_than_4:.4f}")

Probability that exactly 4 recover=0.0330
Probability that more than 4 recover=0.0332

In [56]:
from scipy.stats import binom
n=50
k=0
p=0.65

# Calculate binomial probability
probability=binom.pmf(k,n,p)

print(f"The probability that exactly {k} out of {n} patiant  is: {probability:.25f}")

The probability that exactly 0 out of 50 patiant  is: 0.0000000000000000000000160

In [57]:
n=50
k=15
p=0.2
prob_more_than_15=1-binom.cdf(k,n,p)
print(f"Probability that more than 15 follow up call={prob_more_than_15:.4f}")

Probability that more than 15 follow up call=0.0308

In [58]:
n=50
k=40
p=0.65
prob_more_than_40=1-binom.cdf(k,n,p)
print(f"Probability that more than 40 recover={prob_more_than_40:.4f}")

Probability that more than 40 recover=0.0067

In [59]:
n=50
k=9
p=0.2
prob_than_fewer_than_10=binom.cdf(k,n,p)
print(f"Probability that more than 40 recover={prob_than_fewer_than_10:.4f}")

Probability that more than 40 recover=0.4437

In [60]:
# A blindfolded marksman find that on the average,he hits the target '4' timd out of '5' If he fires '4' shots, what is a probability of (a) more than '2' hits and (b) at least '3' misses

n=4
p=4/5
k=2
P_more_than_2=1-binom.cdf(k,n,p)
print(f"Probability that more than 40 recover={P_more_than_2:.4f}")

Probability that more than 40 recover=0.8192

In [61]:
n=4
p=1/5
k=2
P_more_than_2=1-binom.cdf(k,n,p)
print(f"Probability that more than 40 recover={P_more_than_2:.4f}")

Probability that more than 40 recover=0.0272