In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df_2015 = pd.read_csv("marathon_results_2015.csv")
df_2016 = pd.read_csv("marathon_results_2016.csv")
df_2017 = pd.read_csv("marathon_results_2017.csv")

df =pd.concat([df_2015, df_2016, df_2017], ignore_index=True)
Original_row_count = len(df)
Original_row_count
df.describe()

         Unnamed: 0           Age       Overall        Gender      Division
count  53008.000000  79638.000000  79638.000000  79638.000000  79638.000000
mean   13251.666692     42.415166  13273.683417   6693.365064   1618.782792
std     7651.406646     11.355453   7663.512720   3927.594786   1448.369424
min        0.000000     18.000000      1.000000      1.000000      1.000000
25%     6625.750000     34.000000   6637.250000   3319.000000    510.000000
50%    13251.500000     42.000000  13273.500000   6637.000000   1179.500000
75%    19877.250000     50.000000  19910.000000   9955.000000   2219.000000
max    26597.000000     84.000000  26629.000000  14581.000000   6004.000000

In [18]:
sampled_df = df.sample(frac=0.1, random_state=42)
sampled_row_count = len(sampled_df)
sampled_row_count
sampled_df.describe()

         Unnamed: 0          Age       Overall        Gender     Division
count   5338.000000  7964.000000   7964.000000   7964.000000  7964.000000
mean   13118.205882    42.542315  13158.809518   6671.547464  1590.182195
std     7671.334020    11.359142   7669.737157   3925.692794  1431.617846
min        6.000000    18.000000      2.000000      1.000000     1.000000
25%     6393.500000    34.000000   6457.000000   3335.000000   498.000000
50%    13255.000000    43.000000  13321.000000   6580.500000  1159.000000
75%    19775.500000    51.000000  19778.250000   9937.250000  2155.250000
max    26593.000000    82.000000  26628.000000  14578.000000  6002.000000

In [ ]:
df.head()

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Unnamed: 8
24038,24038.0,31350,"Labonte, Laura R.",34,F,Charlestown,MA,USA,NaN,NaN,...,3:22:19,3:56:22,4:29:25,0:10:49,-,4:43:30,24039,10561,5235,NaN
20218,20218.0,21352,"Vargas, Mario",64,M,Shaker Heights,OH,USA,NaN,NaN,...,2:52:26,3:24:14,3:54:58,0:09:28,-,4:08:04,20219,11836,568,NaN
23755,23755.0,27235,"Wilkins, Stephen D.",53,M,Dorchester,MA,USA,NaN,NaN,...,3:14:37,3:49:59,4:24:08,0:10:40,-,4:39:30,23756,13348,1896,NaN
1447,1447.0,4337,"Johnson, David T",32,M,Brandon,FL,USA,NaN,NaN,...,2:00:46,2:21:31,2:43:11,0:06:39,-,2:54:17,1448,1376,1108,NaN
51719,NaN,26089,"Bashor, Mari W",67,F,Sacramento,CA,USA,NaN,NaN,...,3:35:49,4:17:13,4:56:18,0:11:58,5:13:34,5:13:34,25121,11285,87,NaN

In [11]:
sampled_df.head()

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Unnamed: 8
24038,24038.0,31350,"Labonte, Laura R.",34,F,Charlestown,MA,USA,NaN,NaN,...,3:22:19,3:56:22,4:29:25,0:10:49,-,4:43:30,24039,10561,5235,NaN
20218,20218.0,21352,"Vargas, Mario",64,M,Shaker Heights,OH,USA,NaN,NaN,...,2:52:26,3:24:14,3:54:58,0:09:28,-,4:08:04,20219,11836,568,NaN
23755,23755.0,27235,"Wilkins, Stephen D.",53,M,Dorchester,MA,USA,NaN,NaN,...,3:14:37,3:49:59,4:24:08,0:10:40,-,4:39:30,23756,13348,1896,NaN
1447,1447.0,4337,"Johnson, David T",32,M,Brandon,FL,USA,NaN,NaN,...,2:00:46,2:21:31,2:43:11,0:06:39,-,2:54:17,1448,1376,1108,NaN
51719,NaN,26089,"Bashor, Mari W",67,F,Sacramento,CA,USA,NaN,NaN,...,3:35:49,4:17:13,4:56:18,0:11:58,5:13:34,5:13:34,25121,11285,87,NaN

In [16]:
#systematic random sample

sample_df_systematic = df.iloc[::7, :]
sample_df_systematic_row_count = len(sample_df_systematic)
print(sample_df_systematic_row_count)
sample_df_systematic.head()
sample_df_systematic.describe()

11377

         Unnamed: 0           Age       Overall        Gender      Division
count   7573.000000  11377.000000  11377.000000  11377.000000  11377.000000
mean   13249.418460     42.552430  13271.516305   6711.163312   1610.701767
std     7652.275538     11.416412   7663.896809   3933.488036   1442.123163
min        0.000000     18.000000      1.000000      1.000000      1.000000
25%     6622.000000     34.000000   6637.000000   3346.000000    509.000000
50%    13251.000000     43.000000  13273.000000   6648.000000   1180.000000
75%    19873.000000     51.000000  19909.000000   9997.000000   2198.000000
max    26593.000000     81.000000  26623.000000  14574.000000   6003.000000

In [21]:
#stratified random sample
total_males = len(df[df["M/F"] == "M"])
total_females = len(df[df["M/F"] == "F"])

sample_size = int(0.1 * Original_row_count)
sample_males = int(0.1 * total_males)
sample_females = int(0.1 * total_females)

print(sample_size, sample_males, sample_females)

7963 4348 3615

In [22]:
male_sample = df[df["M/F"] == "M"].sample(n=sample_males, random_state=42)
female_sample = df[df["M/F"] == "F"].sample(n=sample_females, random_state=42)
print(len(male_sample), len(female_sample))

4348 3615

In [26]:
combined_sample_MF = pd.concat([male_sample,female_sample], ignore_index=True)
combined_sample_MF_len = len(combined_sample_MF)
combined_sample_MF_len

7963

In [35]:
#clustered sampling
unique_countries = df["Country"].unique()
print(len(unique_countries),unique_countries)

105 <StringArray>
['ETH', 'KEN', 'USA', 'UKR', 'RSA', 'ITA', 'RUS', 'JPN', 'CAN', 'BEL',
 ...
 'BUL', 'ALG', 'NCA', 'BAR', 'GRN', 'PAR', 'TCA', 'KUW', 'MGL', 'NGR']
Length: 105, dtype: str

In [40]:
np.random.seed(101)
selected_countries = np.random.choice(unique_countries,size=len(unique_countries)//5, replace=False)
selected_countries

array(['CYP', 'KEN', 'TCA', 'LIE', 'SMR', 'LUX', 'POR', 'PAN', 'ISR',
       'CHN', 'RUS', 'EGY', 'FLK', 'GER', 'BER', 'SUI', 'BDI', 'CRO',
       'ISL', 'PER', 'MEX'], dtype=object)

In [41]:
sample_df = df[df["Country"].isin(selected_countries)]
sample_row_count = len(sample_df)
print(sample_row_count)

2327